ANADIR=analyse
CPDIR=cp
CDDIR=cd
all :  main.tex $(ANADIR)/TADcouleur.tex $(ANADIR)/TADpion.tex $(ANADIR)/TADposition.tex $(ANADIR)/TADplateau.tex $(ANADIR)/TADcoups.tex $(ANADIR)/TADcoup.tex $(CPDIR)/couleur/CPTADcouleur.tex $(CPDIR)/coup/CPTADcoup.tex $(CPDIR)/pion/CPTADpion.tex $(CPDIR)/plateau/CPTADplateau.tex $(CPDIR)/faireUnePartie/CPfaireUnePartie.tex $(CPDIR)/obtenirCoup/signatureObtenirCoups.tex
	pdflatex main.tex --shell-escape
	pdflatex main.tex --shell-escape

